version: "3.9"

services:
  auth:
    container_name: "authorization-BE"
    build: .
#    command: ./wait_psql.sh db ./auth-app
    command: ./auth-app
    restart: always
    networks:
      - new
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "8008:8008"
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: postgres:15-alpine
    container_name: "auth_db"
    networks:
      new:
        aliases:
          - database
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5436:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d qtr_portal -U qtr_portal" ]
      interval: 5s
      retries: 5
    restart: always

  migrate:
    image: migrate/migrate
    networks:
      - new
    volumes:
      - .:/migrations
    command: [ "-path", "/migrations", "-database",  "postgres://postgres:postgres@db:5432/postgres?sslmode=disable", "up" ]
    links:
      - db
    depends_on:
      - db

networks:
  new:

volumes:
  postgres_data:
