definitions:
  coreModel.User:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - name
    - password
    - username
    type: object
  coreModel.UserIdResponse:
    properties:
      id:
        type: integer
    type: object
  coreModel.UserLogOutRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  coreModel.UserSignInRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  jwtModel.JWTTokenResponse:
    properties:
      token:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/jwt/get:
    get:
      consumes:
      - application/json
      description: get existing jwt token for user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/jwtModel.JWTTokenResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: get jwt token
      tags:
      - jwt
  /v1/jwt/revoke:
    delete:
      consumes:
      - application/json
      description: revoke existing jwt token for user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/jwtModel.JWTTokenResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: revoke jwt token
      tags:
      - jwt
  /v1/jwt/update:
    post:
      consumes:
      - application/json
      description: update existing jwt token for user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/jwtModel.JWTTokenResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: update jwt token
      tags:
      - jwt
  /v1/log-out:
    post:
      consumes:
      - application/json
      description: route for logging out from veiia system
      parameters:
      - description: User Info
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/coreModel.UserLogOutRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/coreModel.UserIdResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Log Out core
      tags:
      - core
  /v1/sign-in:
    post:
      consumes:
      - application/json
      description: route for signing in to veiia system
      parameters:
      - description: User Info
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/coreModel.UserSignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/coreModel.UserIdResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Sign in core
      tags:
      - core
  /v1/sign-up:
    post:
      consumes:
      - application/json
      description: route for signing up to veiia system
      parameters:
      - description: User Info
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/coreModel.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/coreModel.UserIdResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Sign up core
      tags:
      - core
swagger: "2.0"
